In [1]:
import numpy as np

In [2]:
# Do not change these variables
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])
w = np.array([[1],[8],[0],[5]])

In [3]:
# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

dimensions = {
    'A': A.shape,
    'B': B.shape,
    'C': C.shape,
    'D': D.shape,
    'u': u.shape,
    'v': v.shape,
    'w': w.shape
}

dimensions

{'A': (2, 3),
 'B': (2, 2),
 'C': (3, 2),
 'D': (2, 3),
 'u': (4,),
 'v': (4,),
 'w': (4, 1)}

In [4]:
# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work
alpha = 6

u_plus_v = u+v            # u+v
u_minus_v =  u-v          # u-v
alpha_times_u = alpha * u       # alpha * u, alpha = 6
u_dot_v = np.dot(u, v)              # u . v
norm_u = np.linalg.norm(u)              # ||u|| 

u_plus_v

array([ 9,  7, -4,  9])

In [5]:
# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

A_plus_C = None             # A + C
A_minus_Ctranspose =  A - C.T  # A - C.T
Ctranspose_plus_3D = C.T + 3*D   # C.T + 3*D
B_times_A = np.dot(B, A)            # B*A
B_times_Atranspose = None  # B*A.T

A_minus_Ctranspose

array([[-4, -7, -3],
       [ 3,  6,  4]])

In [6]:
# Q4: (bonus)

B_times_C = None            # B*C
C_times_B = np.dot(C, B)             # C*B
B_exp_4 = np.dot(np.dot(np.dot(B, B), B), B)               # B^4
A_times_Atranspose = np.dot(A, A.T)   # A*A.T
Dtranspose_times_D = np.dot(D.T, D)   # D.T*D

Dtranspose_times_D

array([[10, -4,  0],
       [-4,  8,  8],
       [ 0,  8, 10]])